config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :path => 'user' do
    collection do
  		get 'search'
  	end
  end
  resources :profiles, :shallow => true do
    resources :posts, :path => 'conversation' do
      resources :messages, :path => 'reply' do
      end
    end
  end
  get "search" => "search#show", as: :search
  root 'profiles#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
  extend FriendlyId
	friendly_id :slug_candidates, use: :slugged
  def slug_candidates
    [
      :id
    ]
  end
	def should_generate_new_friendly_id?
    line1_changed?
  end
  belongs_to :user
  has_many :posts, -> { order "created_at DESC" }, dependent: :destroy
  validates :line1, uniqueness: true, length: { maximum: 48 }, format: { with: /\A[a-z0-9_]+\Z/ }
  include PgSearch
  pg_search_scope :search, :against => [:line2, :line3, :line11, :line12, :line13]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :find_profile, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@profiles = Profile.all.order("created_at ASC").limit(4)
	end

	def show
		@profile = Profile.friendly.find(params[:id])
		@messages = Message.where(profile_id: @profile)
		@posts = Post.where(profile_id: @profile)
		@posts = Post.all.order("created_at DESC")
		@messages = Message.all.order("created_at DESC")
	end

	def new
		@profile = current_user.profile.build
	end

	def create
		@profile = current_user.profile.build(user_params)

		if @profile.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @profile.update(profile_params)
			redirect_to @profile, :notice => "Your Profile Information is changed. You can change it again if you want."
		else
			render 'edit'
		end
	end

	private

	def find_profile
		@profile = Profile.friendly.find(params[:id])
	end

	def profile_params
		params.require(:profile).permit(:line1, :line2, :line3, :line4, :line5, :line6, :line7, :line8, :line9, :line10, :line11, :line12, :line13, :line14, :line15, :line16, :slug)
	end
end

app/views/profiles/edit.html+phone.haml
- if user_signed_in?
  - if @profile.user == current_user
    %p#official-m You are Editing your Profile Information:
    .form-style-send-post3-m
      = simple_form_for @profile do |f|
        %h1= f.input :line2, label: "Change Your Name:", :input_html => {class: 'login3-m'}
        %h1= f.input :line3, label: "Boy or Girl:", :input_html => {class: 'login3-m'}
        %h1= f.input :line11, label: "Add Your Address or Location:", :input_html => {class: 'login3-m'}
        %h1= f.input :line12, label: "Which Games do you Play:", :input_html => {class: 'login3-m'}
        %h1= f.input :line13, label: "Your In-Game names & ID numbers:", :input_html => {class: 'login3-m'}
        %h1= f.input :line14, label: "Your Games Statistics:", :input_html => {class: 'login3-m'}
        %h1= f.input :line15, label: "Other Social Media details:", :input_html => {class: 'login3-m'}
        = submit_tag "Change Now", name: nil, class: "button-m2"

  - else
    %h1 We're Sorry but This Page doesn't exist.

app/views/profiles/edit.html.haml
- if user_signed_in?
  - if @profile.user == current_user
    %p#official You are Editing your Profile Information:
    .form-style-send-post3
      = simple_form_for @profile do |f|
        %h4= f.input :line2, label: "Change Your Name:", :input_html => {class: 'login3'}
        %h4= f.input :line3, label: "Boy or Girl:", :input_html => {class: 'login3'}
        %h4= f.input :line11, label: "Add Your Address or Location:", :input_html => {class: 'login3'}
        %h4= f.input :line12, label: "Which Games do you Play:", :input_html => {class: 'login3'}
        %h4= f.input :line13, label: "Your In-Game names & ID numbers:", :input_html => {class: 'login3'}
        %h4= f.input :line14, label: "Your Games Statistics:", :input_html => {class: 'login3'}
        %h4= f.input :line15, label: "Other Social Media details:", :input_html => {class: 'login3'}
        = f.button :submit, "Submit Change", class: 'btn-lg btn-default'

  - else
    %h3 We're Sorry but This Page doesn't exist.

app/views/profiles/index.html+phone.haml
- if user_signed_in?
  %p#intro2-m
    #{current_user.profile.line2}, You're logged in.
    %br/
  %p#intro2-m
    Search Girls and Boys around you who play your favourite games that you Play. Just Type the location & game name you want to search.
  %form{:action => search_path, :method => "get", class: "wrapper-search", role: "search" }
    %p
      = text_field_tag :search, params[:search], class: "search-m", placeholder: "Type Search location name & Games you play & press enter."
    %br/
  %p#official-m
    Search Game Examples: PUBG Mobile, Pubg Mobile Lite, Free Fire, COD Mobile etc.(Any Game you want)
    Search Game Examples: Rajiv Chowk, New Delhi, India etc. (Search Any Place you want)
    %br/
  %p#official-m
    = link_to "Go to your Profile", current_user.profile
    %br/
  %p#official-m
    = link_to "See Received & Sent Messages", current_user
    %br/
  %p#official-m
    = link_to "Edit Your Email or Password", edit_user_registration_path
    %br/

- else
  %p#instavoto-m
    Search Girls and Boys around you who play your favourite games that you Play. Just Type the location & game name you want to search.
  %form{:action => search_path, :method => "get", class: "wrapper-search", role: "search" }
    %p
      = text_field_tag :search, params[:search], class: "search-m", placeholder: "Type Search location name & Games you play & press enter."
    %br/
  %p#official-m
    Search Game Examples: PUBG Mobile, Pubg Mobile Lite, Free Fire, COD Mobile etc.(Any Game you want)
    %br/
  %p#official-m
    Search Location Examples: Rajiv Chowk, New Delhi, India etc. (Search Any Place you want)
    %br/

app/views/profiles/index.html.haml
- if user_signed_in?
  %p#instavoto2
    #{current_user.profile.line2}, You're logged in.
    %br/
  .form-style-instavoto2
    %p#instavoto
      Search Girls and Boys around you who play your favourite games that you Play. Just Type the location & game name you want to search.
    %form{:action => search_path, :method => "get", class: "wrapper-search", role: "search" }
      %p
        = text_field_tag :search, params[:search], class: "search", placeholder: "Type Search location name & Games you play & press enter."
      %br/
    %p#official
      Search Game Examples: PUBG Mobile, Pubg Mobile Lite, Free Fire, COD Mobile etc.(Any Game you want)
      Search Game Examples: Rajiv Chowk, New Delhi, India etc. (Search Any Place you want)
      %br/
  %p#official
    = link_to "Go to your Profile", current_user.profile
    %br/
  %p#official
    = link_to "See Received & Sent Messages", current_user
    %br/
  %p#official
    = link_to "Edit Your Email or Password", edit_user_registration_path
    %br/

- else
  .form-style-instavoto2
    %p#instavoto
      Search Girls and Boys around you who play your favourite games that you Play. Just Type the location & game name you want to search.
    %form{:action => search_path, :method => "get", class: "wrapper-search", role: "search" }
      %p
        = text_field_tag :search, params[:search], class: "search", placeholder: "Type Search location name & Games you play & press enter."
      %br/
    %p#official
      Search Game Examples: PUBG Mobile, Pubg Mobile Lite, Free Fire, COD Mobile etc.(Any Game you want)
      Search Location Examples: Rajiv Chowk, New Delhi, India etc. (Search Any Place you want)
      %br/

app/views/profiles/new.html+phone.haml
%h3 Sorry but this page doesn't exist.

app/views/profiles/new.html.haml
%h3 Sorry but this page doesn't exist.

app/views/profiles/show.html+phone.haml
- if user_signed_in?
  - if @profile.user == current_user
    %p#official-m
      = link_to "Add your Location & All other Games related information from this link:", edit_profile_path(@profile)
            
    .form-style-4-white
      #posts_mobile
        .form-style-user-m
          %p#official-m
            Name: #{@profile.line2}
          %p#official-m
            Profile Picture:
            = image_tag(@profile.user.image.url(:small), class: "img-circular")
        .form-style-upload-profile-m
          = simple_form_for @profile.user do |f|
            %h1= f.error_notification
            .form-inputs
              %h1= f.input :image, label: "Change Profile Picture from here:", :input_html => {class: 'login3-m'}
              = submit_tag "Change Now", name: nil, class: "button-m4"
              
      %p#official-m Gender: #{@profile.line3}
      %p#official-m Location: #{@profile.line11}
      %p#official-m Games You Play: #{@profile.line12}
      %p#official-m Your In-Game Names & ID Numbers: #{@profile.line13}
      %p#official-m Games Statistics: #{@profile.line14}
      %p#official-m Other Social Media details: #{@profile.line15}

  - else    
    .form-style-user-m
      %p#official-m Name: #{@profile.line2}
      %p#official-m
        Profile Picture:
        = image_tag(@profile.user.image.url(:small), class: "img-circular")
    %p#official-m Gender: #{@profile.line3}
    %p#official-m Location: #{@profile.line11}
    %p#official-m Games Playing: #{@profile.line12}
    %p#official-m In-Game Names & ID Numbers: #{@profile.line13}
    %p#official-m Games Statistics: #{@profile.line14}
    %p#official-m Other Social Media details: #{@profile.line15} 
    
    .form-style-send-post-m
      = simple_form_for([@profile, @profile.posts.build]) do |f|
        = f.error_notification
        %h1= f.input :line1, label: "Send Message to Start Conversation:", placeholder: "Write here & Click on Send button to Send Message.", :input_html => {class: 'login5-m'}
        = submit_tag "Send Message", class: 'button-m3'  

- else
  %p#official-m Please SignUp or Login to view This User's Profile. You're not allowed to see it without Sign In.

app/views/profiles/show.html.haml
- if user_signed_in?
  - if @profile.user == current_user
    %p#official
      = link_to "Add your Location & All other Games related information from this link:", edit_profile_path(@profile)
            
    .form-style-4-white
      #posts
        .form-style-user
          %p#official
            Name: #{@profile.line2}
          %p#official
            Profile Picture:
            = image_tag(@profile.user.image.url(:small), class: "img-circular")
        .form-style-upload-profile
          = simple_form_for @profile.user do |f|
            %h4= f.error_notification
            .form-inputs
              %h4= f.input :image, label: "Change Profile Picture from here:", :input_html => {class: 'login6'}
              = f.button :submit, "Change Profile Picture", class: 'btn-lg btn-default'
              
      %p#official Gender: #{@profile.line3}
      %p#official Location: #{@profile.line11}
      %p#official Games You Play: #{@profile.line12}
      %p#official Your In-Game Names & ID Numbers: #{@profile.line13}
      %p#official Games Statistics: #{@profile.line14}
      %p#official Other Social Media details: #{@profile.line15}

  - else    
    .form-style-user
      %p#official Name: #{@profile.line2}
      %p#official
        Profile Picture:
        = image_tag(@profile.user.image.url(:small), class: "img-circular")
    %p#official Gender: #{@profile.line3}
    %p#official Location: #{@profile.line11}
    %p#official Games Playing: #{@profile.line12}
    %p#official In-Game Names & ID Numbers: #{@profile.line13}
    %p#official Games Statistics: #{@profile.line14}
    %p#official Other Social Media details: #{@profile.line15} 
    
    .form-style-send-post
      = simple_form_for([@profile, @profile.posts.build]) do |f|
        = f.error_notification
        %h3= f.input :line1, label: "Send Message to Start Conversation:", placeholder: "Write here & Click on Send button to Send Message.", :input_html => {class: 'login5'}
        = f.button :submit, "Send Message", class: 'btn-lg btn-default'  

- else
  %p#official Please SignUp or Login to view This User's Profile. You're not allowed to see it without Sign In.