config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :path => 'user' do
    collection do
  		get 'search'
  	end
  end
  resources :profiles, :shallow => true do
    resources :posts, :path => 'conversation' do
      resources :messages, :path => 'reply' do
      end
    end
  end
  get "search" => "search#show", as: :search
  root 'profiles#index'
end

app/models/post.rb
class Post < ApplicationRecord
  before_create :randomize_id
  attr_accessor :image
  belongs_to :user
  belongs_to :profile
  has_many :messages, -> { order "created_at ASC" }, dependent: :destroy
  validates :line1, length: { maximum: 9000 }, presence: true, if: -> { image.blank? }
  mount_uploader :image, ImageUploader
  private
  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000_000_000)
    end while Post.where(id: self.id).exists?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:create]

	def create
		@profile = Profile.friendly.find(params[:profile_id])
		@post = Post.create(params[:post].permit(:image, :line1))
		if user_signed_in?
			@post.user_id = current_user.id
			@post.profile_id = @profile.id
		else
			@post.profile_id = @profile.id
		end

		if @post.save
			redirect_back fallback_location: :back, :notice => "You've Successfully Sent the Message. See it in Messages."
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to user_path(current_user)
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:line1, :line2, :line3, :image)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html+phone.haml
= simple_form_for([@profile, @profile.posts.build]) do |f|
	= f.error_notification
	%h4= f.input :image, label: "Upload and Send Photo/Post from below:", input_html: { class: 'login3' }
	= f.input :line1, label: false, placeholder: "Write Photo/Post Caption", input_html: { class: 'login4' }
	= f.button :submit, "Send Post", class: 'btn-lg btn-default'

app/views/posts/_form.html.haml
= simple_form_for([@profile, @profile.posts.build]) do |f|
	= f.error_notification
	%h4= f.input :image, label: "Upload and Send Photo/Post from below:", input_html: { class: 'login3' }
	= f.input :line1, label: false, placeholder: "Write Photo/Post Caption", input_html: { class: 'login4' }
	= f.button :submit, "Send Post", class: 'btn-lg btn-default'

app/views/posts/edit.html+phone.haml
= simple_form_for @post do |f|
	= f.input :image, label: "Add Photo"
	= f.input :line1, label: "Reply to thread"
	= f.button :submit, class: "button"

app/views/posts/edit.html.haml
= simple_form_for @post do |f|
	= f.input :image, label: "Add Photo"
	= f.input :line1, label: "Reply to thread"
	= f.button :submit, class: "button"

app/views/posts/new.html+phone.haml
%p#official-m2 You haven't Uploaded a Post/Photo or Written a Message to Send. Please Go Back and Write or Upload Something to Send.

app/views/posts/new.html.haml
%h3 You haven't Uploaded a Post/Photo or Written a Message to Send. Please Go Back and Check Again.

app/views/posts/show.html+phone.haml
- if user_signed_in?
  - if @post.profile.user == current_user
    - if @post.image.present?
      #post_show_mobile
        %p.username
          Sent by
          = link_to @post.user.profile.line2, @post.user.profile
          on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
        .clearfix
          .post_description
          - if @post.line1.present?
            %h1= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }
            .post_image_description
              = image_tag @post.image.url
            %h1 Caption: #{@post.line1}
          - else
            %h1= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }
            .post_image_description
              = image_tag @post.image.url

      - if @post.user_id.present?
        %p#official-m3 See Messages Sent and Received from below:
        #comments-m
          - @post.messages.each do |message|
            - if message.user == current_user
              .message
                %p#official-m3 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
            - else
              .message
                %p#official-m3 #{@post.user.name}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
        = simple_form_for([@post, @post.messages.build]) do |f|
          = f.input :line1, label: false, placeholder: "Write your Message to reply & Send from below.", :input_html => {class: 'login5-m'}
          = submit_tag "Reply Now!", class: 'button-m3'

      - else
        %h1 You can't Reply because the User who Sent you this wasn't Registered or Logged in.


    - else
      #post_show_mobile
        %p.username
          Sent by
          = link_to @post.user.profile.line2, @post.user.profile
          on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
        .clearfix
          .post_description
            %h1 #{@post.line1}
          .post_data
            %h1= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }

      - if @post.user_id.present?
        #comments-m
          - @post.messages.each do |message|
            - if message.user == current_user
              .message
                %p#official-m3 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
            - else
              .message
                %p#official-m3 #{@post.user.profile.line2}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}

        = simple_form_for([@post, @post.messages.build]) do |f|
          = f.input :line1, label: false, placeholder: "Write your Message to reply & Send from below.", :input_html => {class: 'login5-m'}
          = submit_tag "Reply Now!", class: 'button-m3'
      - else
        %h1 You can't Reply because the User who Sent you this wasn't Registered or Logged in.

  - elsif @post.user == current_user
    - if @post.image.present?
      #post_show_mobile
        %p.username
          Sent by You to #{@post.profile.user.name} on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
        .clearfix
          - if @post.line1.present?
            %h1= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }
            .post_image_description
              = image_tag @post.image.url
            %h1 Caption: #{@post.line1}
          - else
            %h1= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }
            .post_image_description
              = image_tag @post.image.url

      %p#official-m3 See Messages by #{@post.profile.user.name} from below:
      #comments
        - @post.messages.each do |message|
          - if message.user == current_user
            .message
              %p#official-m3 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
          - elsif message.user == @post.profile.user
            .message
              %p#official-m3 #{@post.profile.user.name}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago)
    - else
      #post_show_mobile
        %p.username
          Sent by You to #{@post.profile.user.name} on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
        .clearfix
          %h1= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }
          .post_description
            %h1 You: #{@post.line1}

      %p#official-m3 See Replies by #{@post.profile.user.name} to your Message below:
      #comments
        - @post.messages.each do |message|
          - if message.user == current_user
            .message
              %p#official-m3 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
          - elsif message.user == @post.profile.user
            .message
              %p#official-m3 #{@post.profile.user.name}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago)

    = simple_form_for([@post, @post.messages.build]) do |f|
      = f.input :line1, label: false, placeholder: "Write your Message to reply & Send from below.", :input_html => {class: 'login5-m'}
      = submit_tag "Reply Now!", class: 'button-m3'

  - else
    %h3 Sorry but this Page doesn't exist.

- else
  %h3 Sorry but this Page doesn't exist.

app/views/posts/show.html.haml
- if user_signed_in?
  - if @post.profile.user == current_user
    - if @post.image.present?
      #post_show
        %p.username
          Sent by
          = link_to @post.user.profile.line2, @post.user.profile
          on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
        .clearfix
          .post_description
          - if @post.line1.present?
            .post_image_description
              = image_tag @post.image.url
              %h3 Caption: #{@post.line1}
            .post_data
              %h2= link_to "Delete Now", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }
          - else
            .post_image_description
              = image_tag @post.image.url
            .post_data
              %h2= link_to "Delete Now", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }

      - if @post.user_id.present?
        %h3 See Messages Sent and Received for this Post/Photo below:
        #comments
          - @post.messages.each do |message|
            - if message.user == current_user
              .message
                %h4 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
            - else
              .message
                %h4 #{@post.user.name}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
        = render "messages/form"
      - else
        %h3 You can't Reply because the User who Sent you this wasn't Registered or Logged in.


    - else
      #post_show
        %p.username          
          Sent by
          = link_to @post.user.profile.line2, @post.user.profile
          on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
          
        .clearfix
          .post_description
            %h3 #{@post.line1}
          .post_data
            %h3= link_to "Delete Now", post_path(@post), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }

      - if @post.user_id.present?
        #comments
          - @post.messages.each do |message|
            - if message.user == current_user
              .message
                %h4 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
            - else
              .message
                %h4 #{@post.user.profile.line2}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}

        = render "messages/form"
      - else
        %h3 You can't Reply because the User who Sent you this wasn't Registered or Logged in.

  - elsif @post.user == current_user
    - if @post.image.present?
      #post_show
        %p.username
          Sent by You to #{@post.profile.user.name} on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
        .clearfix
          - if @post.line1.present?
            .post_image_description
              = image_tag @post.image.url
              %h3 Caption: #{@post.line1}
          - else
            .post_image_description
              = image_tag @post.image.url

      %h3 See Messages by #{@post.profile.user.name} from below:
      #comments
        - @post.messages.each do |message|
          - if message.user == current_user
            .message
              %h4 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
          - elsif message.user == @post.profile.user
            .message
              %h4 #{@post.profile.user.name}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago)
    - else
      #post_show
        %p.username
          Sent by You to #{@post.profile.user.name} on
          = @post.created_at
          (#{time_ago_in_words(@post.created_at)} ago).
        .clearfix
          .post_description
            %h3 You: #{@post.line1}

      %h3 See Replies by #{@post.profile.user.name} to your Message:
      #comments
        - @post.messages.each do |message|
          - if message.user == current_user
            .message
              %h4 You: #{message.line1} (Sent - #{time_ago_in_words(message.created_at)} ago) #{link_to "Delete", message_path(message), method: :delete, data: { confirm: "You want to Delete. Are you sure?" }}
          - elsif message.user == @post.profile.user
            .message
              %h4 #{@post.profile.user.name}: #{message.line1} (Received - #{time_ago_in_words(message.created_at)} ago)

    = render "messages/form"
  - else
    %h3 Sorry but this Page doesn't exist.

- else
  %h3 Sorry but this Page doesn't exist.